### ISSUE TITLE
elm make Main.elm

### ISSUE THREAD

**Issue by summitmann** [w0rm/elm-flatris#10]
In Readme.md: under... 
Touch support (tested on iOS)
For a touch support compile to html elm make --output elm-flatris.html 

Shouldn't it be Changed to:
For a touch support compile to html elm make Main.elm --output elm-flatris.html

**Comment by w0rm** [comment]
@summitmann thanks! it was a typo

**Comment by summitmann** [comment]
You are welcome..
Is there an easy way to implement your touch screen capabilities to the elm
snake game or the elm asteroids game?

Snake:  http://share-elm.com/sprout/568d0a72e4b070fd20da8052
Or,
https://github.com/liubko/elm-snake

Would it be easier with this version of snake...

http://elm-by-example.org/chapter13snake.html

Asteroids:
need to find version I like best...

Thanks for your great work...

Truly remarkable!

Sincerely,

Mark Mann, Ph.D., Ed.D..
Email: mmann2@twu.edu, mmann@summit.edu
office: 940.898.2578
cell: 918.231.1147

**Comment by summitmann** [comment]
Andrey,

Here is the link to the best implementation of Asteroids that I have seen.

https://github.com/summitmann/asteroids https://github.com/summitmann/asteroids

I have forked it there… 

I am making a presentation tomorrow about the value of Elm in game development to a group of 
academics.  Obviously, I am more of an end user than a programmer.  However,  I have created a website to feature
these apps.  May I also feature your flatris implementation.  As I have stated before, I am truly impressed with your work.  

My goal is to write a book on how to implement elm in game development.  Your breakthru pioneering work to make elm apps work with 
touchscreen applications is great.

Sincerely,

Mark Mann, Ph.D. 
http://vita.summit.edu http://vita.summit.edu/

**Comment by summitmann** [comment]
Hi this is mark mann again.

ian hobson is the programmer that has written best elm asteroids and elm snake implementation. no touch screen though… 

https://github.com/irh https://github.com/irh

His snake program is at:

https://github.com/irh/snake https://github.com/irh/snake

You should def. work with him…

Mark Mann
