### ISSUE TITLE
Runtime exception

### ISSUE THREAD

**Issue by tsoposki** [w0rm/elm-flatris#15]
When i pressed pause i got runtime exception:

`Main.elm:2417 Uncaught TypeError: Cannot read property 'ctor' of null 

step @ Main.elm:2417
work @ Main.elm:2533`

How is it possible, elm is guaranteeing no run time exception?

**Comment by w0rm** [comment]
@tsoposki it looks to be this bug https://github.com/elm-lang/core/issues/628

**Comment by tsoposki** [comment]
@w0rm great, thank you! Hope it will be fixed soon.
