### ISSUE TITLE
Page down/up with arrow keys

### ISSUE THREAD

**Issue by NicolasFrancaX** [w0rm/elm-flatris#17]
When you play elm-flatris using arrow keys, the page move together.

It hinders the gameplay.

I want contribute with elm-flatris, but I don't know very much html / js / elm. But with help I can commit something to help in this!

**Comment by w0rm** [comment]
@NicolasFrancaX I don't have a nice idea how to fix this issue. The page moves because of the default scrolling behaviour of the browser.

**Comment by NicolasFrancaX** [comment]
In http://skidding.github.io/flatris/ the page don't move like in elm-flatris.

I'll find a solution.

**Comment by w0rm** [comment]
@NicolasFrancaX it just [prevents default on keydown](https://github.com/skidding/flatris/blob/0d890fb8e29b09ae3df21e8730562609a25c079c/src/components/FlatrisGame.jsx#L143) but its impossible with [Elm Keyboard module](http://package.elm-lang.org/packages/elm-lang/keyboard/1.0.0/Keyboard)

**Comment by jzarzeckis** [comment]
http://package.elm-lang.org/packages/evancz/elm-html/4.0.1/Html-Events

PreventDefault has been made available in this package.

**Comment by w0rm** [comment]
@natrixnatrix89 this doesn't help much, because these events are only for the elements that are rendered by virtual DOM, not for the global window events.

**Comment by w0rm** [comment]
Fixed with prevent default.
